"""add interrupt runtime

Revision ID: 1b72c59ce4c2
Revises: 3a9297752327
Create Date: 2026-05-28 18:52:01.249882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1b72c59ce4c2'
down_revision: Union[str, Sequence[str], None] = '3a9297752327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('interrupt_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'interrupt_reason')
    # ### end Alembic commands ###