"""add workflow checkpoints

Revision ID: 3a9297752327
Revises: e9828673ab02
Create Date: 2026-05-28 01:10:17.702181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3a9297752327'
down_revision: Union[str, Sequence[str], None] = 'e9828673ab02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_checkpoints', sa.Column('retry_count', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_checkpoints', 'retry_count')
    # ### end Alembic commands ###