"""add runtime metrics

Revision ID: 8a9f633f3c94
Revises: ac7fe010f8fc
Create Date: 2026-05-28 19:45:50.367265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8a9f633f3c94'
down_revision: Union[str, Sequence[str], None] = 'ac7fe010f8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###