"""add retry workflow fields

Revision ID: 8d167bc0dad6
Revises: 4b71f57e129b
Create Date: 2026-05-25 10:09:27.176707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d167bc0dad6'
down_revision: Union[str, Sequence[str], None] = '4b71f57e129b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('workflows', sa.Column('name', sa.String(), nullable=False))
    op.add_column('workflows', sa.Column('result', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('retry_count', sa.String(), nullable=False))
    op.add_column('workflows', sa.Column('max_retries', sa.String(), nullable=False))
    op.add_column('workflows', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflows', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('workflows', 'workflow_id')
    op.drop_column('workflows', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workflows', 'completed_at')
    op.drop_column('workflows', 'started_at')
    op.drop_column('workflows', 'max_retries')
    op.drop_column('workflows', 'retry_count')
    op.drop_column('workflows', 'error')
    op.drop_column('workflows', 'result')
    op.drop_column('workflows', 'name')
    op.drop_column('workflows', 'id')
    # ### end Alembic commands ###