"""add workflow checkpoints

Revision ID: a44d982060da
Revises: 8353930ab4f4
Create Date: 2026-05-25 13:37:43.532798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a44d982060da'
down_revision: Union[str, Sequence[str], None] = '8353930ab4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###