"""add workflow events

Revision ID: ac7fe010f8fc
Revises: 1b72c59ce4c2
Create Date: 2026-05-28 19:41:33.441075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ac7fe010f8fc'
down_revision: Union[str, Sequence[str], None] = '1b72c59ce4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###