"""add workflow checkpoints

Revision ID: e9828673ab02
Revises: f43211090e8a
Create Date: 2026-05-27 02:58:44.072849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e9828673ab02'
down_revision: Union[str, Sequence[str], None] = 'f43211090e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###