"""add workflow checkpoints

Revision ID: f43211090e8a
Revises: a44d982060da
Create Date: 2026-05-27 02:50:47.909430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43211090e8a'
down_revision: Union[str, Sequence[str], None] = 'a44d982060da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_checkpoints', sa.Column('workflow_state', sa.JSON(), nullable=False))
    op.add_column('workflow_checkpoints', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('workflow_checkpoints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_column('workflow_checkpoints', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_checkpoints', sa.Column('state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('workflow_checkpoints', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('workflow_checkpoints', 'status')
    op.drop_column('workflow_checkpoints', 'workflow_state')
    # ### end Alembic commands ###