"""add workflow events table

Revision ID: fc6ef460d5a3
Revises: 8a9f633f3c94
Create Date: 2026-05-28 20:09:13.699655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fc6ef460d5a3'
down_revision: Union[str, Sequence[str], None] = '8a9f633f3c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###